# Generated by Django 4.2.3 on 2023-07-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=250)),
                ('summary', models.TextField(max_length=5000)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
